<a href="https://colab.research.google.com/github/sightes/BIGDATA-UBO2022/blob/main/Arbol_Decision_Spark.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Version Python 

In [3]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [8]:
data=load_iris()
X=data.data
y=data.target
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=50, test_size=0.7)
model=DecisionTreeClassifier()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.9619047619047619
[[37  0  0]
 [ 0 30  4]
 [ 0  0 34]]


### Version Pyspark

In [10]:
%%capture
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!wget 'https://dlcdn.apache.org/spark/spark-3.3.1/spark-3.3.1-bin-hadoop3.tgz' -O 'spark-3.3.1-bin-hadoop3.tgz'
!tar -xvf /content/spark-3.3.1-bin-hadoop3.tgz
!pip install -q findspark 
     

In [11]:
import os 
import findspark 
os.environ['JAVA_HOME']='/usr/lib/jvm/java-8-openjdk-amd64'
os.environ['SPARK_HOME']='/content/spark-3.3.1-bin-hadoop3'
findspark.init()

In [14]:
from pyspark import SparkContext
from pyspark.sql import SQLContext
from pyspark.ml.classification import DecisionTreeClassifier
from pyspark.ml.feature import VectorAssembler
from pyspark.ml.evaluation import MulticlassClassificationEvaluator
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import pandas as pd 

In [ ]:
iris=load_iris()
df_iris=pd.DataFrame(iris.data , columns=iris.feature_names)
df_iris['label']=pd.Series(iris.target)
df_iris.head(3)

In [18]:
sc=SparkContext().getOrCreate()
sqlContext=SQLContext(sc)
data=sqlContext.createDataFrame(df_iris)

/content/spark-3.3.1-bin-hadoop3/python/pyspark/sql/context.py:112: FutureWarning: Deprecated in 3.0.0. Use SparkSession.builder.getOrCreate() instead.
  warnings.warn(
